[package]
name = "bevy-ultralight"
version = "0.1.0"
edition = "2021"

[dependencies]
ul-sys = "=1.2.2"
serde_json = "1.0"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
branch = "main"